### ISSUE TITLE
1050MHz CPU only OC bootloader seems to be invalid

### ISSUE THREAD

**Issue by igr91** [gwlim/archer-c7v4-uboot#1]
Just noticed all other modified bootloaders are 78.8KB in size, but this one is ~165KB. Opened it up with a hex editor and there's clearly something wrong.

This 165KB file is recognized by github as an executable file (whereas the 78.8KB ones aren't)
The first 78.8KB are completely different and you can later read error messages and other stuff in plaintext.

Would you mind checking this file? Just letting you know since people could try to flash this file going straight for the fastest option available without checking and probably brick their routers in the process. 

Thanks.

**Comment by gwlim** [comment]
Thanks for checking
