### ISSUE TITLE
compile/build instructions

### ISSUE THREAD

**Issue by czo** [gwlim/archer-c7v4-uboot#2]
Hi,

Can you tell me, how did you compiled this? I mean, did you found a way to compile only the u-boot from the tp-link's package (ArcherC7V4_1_0_2.tar.bz2 for v4 and ArcherC7V5.tar.bz2 for v5), or we have to wait to compile the complete package?

**Comment by czo** [comment]
Yep, building the whole package (both v4 and v5), produces an useable/flashable u-boot. I will close this.

**Comment by diego-ch** [comment]
do you mind sharing your build system setup?
i'm trying to do the same thing for the c7v5 here and i'm stuck building m4

```
gcc  -I.   -I/home/diegoch/archer_oc/Archer_C7_V5/openwrt/staging_dir/host/include  -O2 -I/home/diegoch/archer_oc/Archer_C7_V5/openwrt/staging_dir/host/include -MT freadahead.o -MD -MP -MF .deps/freadahead.Tpo -c -o freadahead.o freadahead.c

freadahead.c: In function 'freadahead':
freadahead.c:83:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
   83 |  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
      |   ^~~~~
make[8]: *** [Makefile:1399: freadahead.o] Error 1

make[8]: Leaving directory '/home/diegoch/archer_oc/Archer_C7_V5/openwrt/build_dir/host/m4-1.4.16/lib'
make[7]: *** [Makefile:1196: all] Error 2
make[7]: Leaving directory '/home/diegoch/archer_oc/Archer_C7_V5/openwrt/build_dir/host/m4-1.4.16/lib'
make[6]: *** [Makefile:1131: all-recursive] Error 1
make[6]: Leaving directory '/home/diegoch/archer_oc/Archer_C7_V5/openwrt/build_dir/host/m4-1.4.16'
make[5]: *** [Makefile:1084: all] Error 2
make[5]: Leaving directory '/home/diegoch/archer_oc/Archer_C7_V5/openwrt/build_dir/host/m4-1.4.16'
make[4]: *** [Makefile:31: /home/diegoch/archer_oc/Archer_C7_V5/openwrt/build_dir/host/m4-1.4.16/.built] Error 2
make[4]: Leaving directory '/home/diegoch/archer_oc/Archer_C7_V5/openwrt/tools/m4'
make[3]: *** [tools/Makefile:143: tools/m4/compile] Error 2
make[3]: Leaving directory '/home/diegoch/archer_oc/Archer_C7_V5/openwrt'
make[2]: *** [tools/Makefile:141: /home/diegoch/archer_oc/Archer_C7_V5/openwrt/staging_dir/target-mips_r2_uClibc-0.9.33.2/stamp/.tools_install_nnnnn] Error 2

make[2]: Leaving directory '/home/diegoch/archer_oc/Archer_C7_V5/openwrt'
make[1]: *** [/home/diegoch/archer_oc/Archer_C7_V5/openwrt/include/toplevel.mk:158: world] Error 2
make[1]: Leaving directory '/home/diegoch/archer_oc/Archer_C7_V5/openwrt'
make: *** [Makefile:20: build] Error 2
```

**Comment by czo** [comment]
It's nothing "special". According to the age of the source code, i had to create a fresh "install" of a 32 bit Jessie with debootstrap. I really dunno why i had to choose 32 bit, but it's works. Under that version, i can compile TP-Link's original source codes for the v4 revision, without any issue. It's not worked for me on a v5 for first check, but i don't worked on it because i have only one v5.

**Comment by diego-ch** [comment]
alright, thanks for the tip.
I'll set that up on a container and see if it works.
I'm running a c7v5 here as well

**Comment by czo** [comment]
The source code for the v5 seems more likely a v4 for me, because of the different flash layout. So, the compiled v5 source can not produce a bootable uboot for me.

**Comment by diego-ch** [comment]
@czo did you manage to overclock the c7v5?

**Comment by czo** [comment]
The answer is both yes and no. Compilation of the v5 source will produce an usable/bootable uboot, BUT this uboot "did not work" with the flash layout of the v5. The "not working" means, it can not autoboot, but can be booted manually with commands entered over the serial console. I did not wan't to figured out how to replace the flash layout or disable the checking, because i had enough v4 device, and simply replaced the v5 with a v4 one.

**Comment by diego-ch** [comment]
Fair enough, I managed to get the file but didn't want to write it to the router and brick it. How's the performance on the v4? I'm able to max out my isp link via ethernet, 300mbit, but over wifi the router maxes out around 240 mbit.

**Comment by princeestoque** [comment]
hello im trying to overclock my archer c7 v4, but the only the 800mhz was stable, the 1000mhz causes my router to automatically reboot.

**Comment by princeestoque** [comment]
can you help me to compile atlease 960mhz because I'm thinking that my router cant handle 1000mhz and up
